### ISSUE TITLE
Jobrunr  example not working with MongoDB

### ISSUE THREAD

**Issue by vikas-shrivastav** [jobrunr/example-micronaut#3]
Hi,

 I am using the example given here and done following changes but it is still picking InMemoryStorageProvider.

Changes done:
application.yml:
```
datasources:
#  default:
#    url: jdbc:h2:file:/tmp/default
#    driverClassName: org.h2.Driver

  mongodb:
    servers.*.uuid-representation: STANDARD
    uri: mongodb://127.0.0.1:27017/jobrunr
```

build.gradle:

` implementation("io.micronaut.data:micronaut-data-mongodb")
    implementation("io.micronaut.mongodb:micronaut-mongo-reactive")
    `
